In [4]:

import numpy as np
from tensorflow.keras.preprocessing.text import one_hot
from tensorflow.keras.preprocessing.sequence import pad_sequences
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.layers import Flatten
from tensorflow.keras.layers import Embedding


In [5]:

reviews = ['nice food',
        'amazing restaurant',
        'too good',
        'just loved it!',
        'will go again',
        'horrible food',
        'never go there',
        'poor service',
        'poor quality',
        'needs improvement']

sentiment = np.array([1,1,1,1,1,0,0,0,0,0])

In [6]:

one_hot("amazing restaurant",30)

[23, 18]

In [7]:

vocab_size = 30
encoded_reviews = [one_hot(d, vocab_size) for d in reviews]
print(encoded_reviews)

[[12, 21], [23, 18], [20, 20], [4, 18, 18], [2, 17, 17], [4, 21], [12, 17, 4], [19, 10], [19, 19], [22, 8]]


In [18]:

max_length = 3
padded_reviews = pad_sequences(encoded_reviews, maxlen=max_length, padding='post')
print(padded_reviews)

[[12 21  0]
 [23 18  0]
 [20 20  0]
 [ 4 18 18]
 [ 2 17 17]
 [ 4 21  0]
 [12 17  4]
 [19 10  0]
 [19 19  0]
 [22  8  0]]


In [19]:
embeded_vector_size = 5

model = Sequential()
model.add(Embedding(vocab_size, embeded_vector_size, input_length=max_length,name="embedding"))
model.add(Flatten())
model.add(Dense(1, activation='sigmoid'))

In [10]:
X = padded_reviews
y = sentiment

In [11]:

model.compile(optimizer='adam', loss='binary_crossentropy', metrics=['accuracy'])
print(model.summary())

Model: "sequential"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 embedding (Embedding)       (None, 4, 5)              150       
                                                                 
 flatten (Flatten)           (None, 20)                0         
                                                                 
 dense (Dense)               (None, 1)                 21        
                                                                 
Total params: 171
Trainable params: 171
Non-trainable params: 0
_________________________________________________________________
None


In [12]:
model.fit(X, y, epochs=50, verbose=0)

In [13]:
loss, accuracy = model.evaluate(X, y)
accuracy

1/1 [==============================] - 0s 129ms/step - loss: 0.6268 - accuracy: 1.0000


1.0

In [14]:
weights = model.get_layer('embedding').get_weights()[0]
len(weights)

30

In [15]:

weights[13]

array([-0.0333411 , -0.03972577,  0.02009163, -0.00102045, -0.01813938],
      dtype=float32)

In [16]:

weights[4]

array([ 0.07928611,  0.0466    ,  0.02735725,  0.07355542, -0.06281243],
      dtype=float32)

In [17]:

weights[16]

array([-0.02316665, -0.02832258,  0.03477235,  0.02149444,  0.02178781],
      dtype=float32)