In [25]:
import numpy as np
y_predicted =np.array([1,1,0,0,1])
y_true=np.array([0.30,0.7,1,0,0.5])

In [26]:
def mae(y_true,y_predicted):
    total_error=0
    for yt, yp in zip(y_true,y_predicted):
        total_error+=abs(yt-yp)
    print("total error",total_error)

    mae=total_error/len(y_true)
    print("MAE",mae)
    return mae

In [27]:
mae(y_true,y_predicted)

total error 2.5
MAE 0.5


0.5

In [28]:
np.abs(y_predicted-y_true) # absoulute  error 


array([0.7, 0.3, 1. , 0. , 0.5])

In [29]:
np.mean(np.abs(y_predicted-y_true)) #mean error 


0.5

In [30]:
np.sum(np.abs(y_predicted-y_true)) # total error 


2.5

In [31]:
np.log([0.000000000000000000000000000000000000000001])

array([-96.70857391])

In [32]:
epsilon=1e-15

In [33]:

y_predicted_new= [ max(i,epsilon) for i in y_predicted ]
y_predicted_new

[1, 1, 1e-15, 1e-15, 1]

In [34]:
y_predicted_new= [min(i,1-epsilon) for i in y_predicted_new ]
y_predicted_new


[0.999999999999999, 0.999999999999999, 1e-15, 1e-15, 0.999999999999999]

In [35]:
y_predicted_new= np.array(y_predicted_new )
np.log(y_predicted_new)


array([-9.99200722e-16, -9.99200722e-16, -3.45387764e+01, -3.45387764e+01,
       -9.99200722e-16])

In [36]:
-np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))


17.2696280766844

In [37]:
def log_loss(y_true, y_predicted):
    y_predicted_new = [max(i,epsilon) for i in y_predicted]
    y_predicted_new = [min(i,1-epsilon) for i in y_predicted_new]
    y_predicted_new = np.array(y_predicted_new)
    return -np.mean(y_true*np.log(y_predicted_new)+(1-y_true)*np.log(1-y_predicted_new))

In [38]:

log_loss(y_true, y_predicted)

17.2696280766844